name: Deploy para EC2 Privada via Jumpbox

on:
  push:
    branches:
      - master  # Branch monitorada para o deploy
  workflow_dispatch:  # Permite rodar o workflow manualmente pela interface do GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH para Jumpbox
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_PEM }}  # Nome do segredo criado para a chave da instância pública (jumpbox)

      - name: Deploy para instância privada via Jumpbox
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@44.211.251.239 "
            ssh -o StrictHostKeyChecking=no -i /home/ec2-user/chaves-teste.pem ec2-user@10.0.135.192 '
              cd /var/www/atendimentos-app &&
              git pull origin master &&
              docker-compose down &&
              docker-compose up -d --build
            '
          "
