name: Deploy para EC2 Pública

on:
  push:
    branches:
      - master  # Branch monitorada para o deploy
  workflow_dispatch:  # Permite rodar o workflow manualmente pela interface do GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH para EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_PEM }}  # Nome do segredo criado para a chave da instância pública

      - name: Deploy para a instância pública
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 ec2-user@3.95.59.48 '
            if [ ! -d "/home/ec2-user/atendimentos-app" ]; then
              # Diretório não existe, clonar o repositório
              git clone https://github.com/renan230399/atendimentos-app.git /home/ec2-user/atendimentos-app
            fi
            cd /home/ec2-user/atendimentos-app &&
            git pull origin master &&
            docker-compose exec laravel.test npm install &&  # Executar npm dentro do container
            docker-compose exec laravel.test npm run build &&  # Gerar o build do Vite
            docker-compose down &&
            docker-compose up -d --build &&
            docker-compose logs --tail=50  # Exibir os últimos 50 logs após o deploy
          '
