jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências e Build
        run: |
          yarn install
          yarn build

      - name: Configurar SSH para EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_PEM }}

      - name: Garantir que o Docker esteja rodando
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.145.7.112 '
            if ! systemctl is-active --quiet docker; then
              echo "Docker não está rodando. Iniciando o serviço Docker...";
              sudo systemctl start docker;
            else
              echo "Docker já está rodando.";
            fi
          '

      - name: Copiar arquivos para a instância pública (inclui build)
        run: |
          rsync -avz --exclude 'node_modules' --include 'public/build/' -e "ssh -i /dev/shm/.ssh/ssh_key -o StrictHostKeyChecking=no" ./ ec2-user@54.145.7.112:/home/ec2-user/atendimentos-app/

      - name: Reiniciar Docker no EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.145.7.112 '
            cd /home/ec2-user/atendimentos-app &&
            docker-compose down &&
            docker-compose up -d --build
          '

      - name: Verificar containers em execução
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.145.7.112 '
            cd /home/ec2-user/atendimentos-app &&
            docker-compose ps
          '

      - name: Limpar e Semear o Banco de Dados
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.145.7.112 '
            cd /home/ec2-user/atendimentos-app &&
            docker-compose exec laravel.test php artisan migrate:fresh --seed
          '
