name: Deploy para EC2 Pública

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências e Build
        run: |
          npm install
          npm run build

      - name: Configurar SSH para EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_PEM }}

      - name: Atualizar código na EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PEM }}" ec2-user@3.95.59.48 '
            cd /home/ec2-user/atendimentos-app &&
            git pull origin master
          '

      - name: Criar diretório de build no servidor, se não existir
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PEM }}" ec2-user@3.95.59.48 '
            mkdir -p /var/www/html/public/build
          '

      - name: Copiar Build para a instância pública
        run: |
          scp -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PEM }}" -r public/build/* ec2-user@3.95.59.48:/var/www/html/public/build/

      - name: Ajustar permissões no diretório de build
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_PEM }}" ec2-user@3.95.59.48 '
            sudo chown -R www-data:www-data /var/www/html/public/build &&
            sudo chmod -R 755 /var/www/html/public/build
          '

      - name: Reiniciar Docker no EC2
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=120 -o StrictHostKeyChecking=no -o ConnectTimeout=120 ec2-user@3.95.59.48 '
            cd /home/ec2-user/atendimentos-app &&
            docker-compose down &&
            docker-compose up -d --build
          '

      - name: Executar Database Seeder com migrate:fresh
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=120 -o StrictHostKeyChecking=no -o ConnectTimeout=120 ec2-user@3.95.59.48 '
            cd /home/ec2-user/atendimentos-app &&
            docker-compose exec laravel.test php artisan migrate:fresh --seed
          '
