name: Deploy para EC2

on:
  push:
    branches:
      - master  # Branch que vai acionar o deploy
  workflow_dispatch:  # Permite rodar o workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Versão do Node.js que você deseja usar

      - name: Instalar dependências e Build
        run: |
          npm install
          npm run build

      - name: Copiar Build para EC2
        uses: appleboy/scp-action@v1
        with:
          host: ec2-3-95-59-48.compute-1.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY_PEM }}  # Adicione sua chave privada nos Secrets do GitHub
          port: 22
          source: "public/build/*"  # Caminho dos arquivos a serem enviados
          target: "/home/ec2-user/atendimentos-app/public/build/"  # Destino no servidor

      - name: Reiniciar Docker no EC2
        run: |
          ssh -i "chaves-teste.pem" ec2-user@3.95.59.48 'cd /home/ec2-user/atendimentos-app && docker-compose down && docker-compose up -d --build'

      - name: Executar Seeders
        run: |
          ssh -i "chaves-teste.pem" ec2-user@3.95.59.48 'cd /home/ec2-user/atendimentos-app && docker-compose exec laravel.test php artisan db:seed'
