name: Deploy para EC2 Pública

on:
  push:
    branches:
      - master  # Branch monitorada para o deploy
  workflow_dispatch:  # Permite rodar o workflow manualmente pela interface do GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH para EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_PEM }}  # Nome do segredo criado para a chave da instância pública

      - name: Deploy para a instância pública
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=120 -o StrictHostKeyChecking=no -o ConnectTimeout=120 ec2-user@3.95.59.48 '
            if [ ! -d "/home/ec2-user/atendimentos-app" ]; then
              # Clonar o repositório se o diretório não existir
              git clone https://github.com/renan230399/atendimentos-app.git /home/ec2-user/atendimentos-app
            fi
            cd /home/ec2-user/atendimentos-app &&
            git pull origin master &&
            docker-compose down &&
            docker-compose up -d --build  # Subir os containers com o build
          '
